### ISSUE TITLE
Express.js support

### ISSUE THREAD

**Issue by microdee** [Retyped/Retyped#14]
I found Retyped and Bridge.NET recently and I immediately fell in love with them. I tested out if I can write a little node.js server with it and I noticed there's no Express.js present in the Retyped library (while it is there in DefinitelyTyped)
Is there a problem with express.js that prevents Retyped working with it?
Thanks and keep up the good work!

**Found in:**
- [express](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/express)

**Comment by geoffreymcgill** [comment]
Thanks for the feedback!

We'll look into express js to determine why a package is not being created by Retyped. Sometimes a package can also fail because a dependency is failing. 

We will investigate and provide a status report as soon as we know what's failing. Should be quick.

**Comment by microdee** [comment]
nice! looking forward to it! if that'll work it will incredibly speed up coding my near future web projects!

**Comment by AndreyChechel** [comment]
@geoffreymcgill was right, there were some issues connected with the packages **Express.js** depends on. They were fixed.

A Retyped package for **Express.js** has been created and can be installed using NuGet:
https://retyped.com/?q=express#search
https://www.nuget.org/packages/retyped.express

**Comment by microdee** [comment]
wow that was super quick! you guys are the best!

**Comment by geoffreymcgill** [comment]
@microdee Thanks for the feedback and hope this helps with your project. Please spread the word about Retyped and Bridge. These projects are open-source and we're investing a huge amount of time and resources into making them a success, so any help with communicating to the outside world is greatly appreciated.
