### ISSUE TITLE
Support Vue.js library

### ISSUE THREAD

**Issue by geoffreymcgill** [Retyped/Retyped#16]
Request to support Vue.js library.

Resource | Location
---- | ----
Website | https://vuejs.org
GitHub | https://github.com/vuejs/vue
Types | https://github.com/vuejs/vue/tree/dev/types

## See Also

* https://twitter.com/cbsmith402/status/918555049311330304 by [@cbsmith402](https://twitter.com/cbsmith402)

**Comment by ebekker** [comment]
Is this anything that can be previewed or tested out while you guys are working on it?

**Comment by AndreyChechel** [comment]
Hi @ebekker,

We're still in progress of getting  **Vue.js** package generated. It requires a few improvements for Retyped compiler (type resolution process particularly) that we are currently working on. Once we finish it, we'll be able to compile that library and, I believe, many others.

**Comment by AndreyChechel** [comment]
Retyped package for **Vue.js** has been pushed to NuGet:
https://retyped.com/?q=vue#search
https://www.nuget.org/packages/Retyped.vue/

A simple "Hello World" demo project is available [here](https://github.com/Retyped/Demos/tree/master/VueDemo). The demo project uses **require.js** to load **vue** module. Webpack usage will likely require some modifications in Bridge.

Though Vue API is fully supported by Retyped now, it might appear not convenient/natural to use it from within C# program. So the demo project includes [additional entities](https://github.com/Retyped/Demos/tree/master/VueDemo/VueDemo/Extensions) helping to simplify the development process. They're just an example of how we could utilize Vue API in C#. 

We'd appreciate for any ideas and suggestions regarding that. And I hope once we come up with a solid pattern, we'd be able to include additional helpers/entities in **Retyped.vue** package.

**Comment by mzhukovs** [comment]
What about Vuex (store state management for Vue)?

**Comment by mzhukovs** [comment]
What about Vuex (store state management for Vue)?

**Comment by geoffreymcgill** [comment]
Hi @mzhukovs – Please create a new [issue](https://github.com/Retyped/Retyped/issues/new), similar to this one including the **Resource** and **Location** details, requesting support for [Vuex](https://vuex.vuejs.org/en/) and we'll take a look.
