### ISSUE TITLE
requestAnimationCallback expects an interface instead of a lambda

### ISSUE THREAD

**Issue by R2D221** [Retyped/Retyped#25]
requestAnimationCallback needs an interface to work, forcing me to create a class just for the callback, instead of a lambda like other callback functions.

**Found in:**
- [Retyped.dom](https://raw.githubusercontent.com/Microsoft/TypeScript/v2.3.4/lib/lib.dom.d.ts)

The definition for the callback looks like this:

    interface FrameRequestCallback {
        (time: number): void;
    }

This should be converted to a delegate.

**Comment by AndreyChechel** [comment]
Hi @R2D221,

Thanks for a nice suggestion!

As for all similar interfaces - I have some concerns about replacing them with delegates by default, we should investigate it first. There could be potential issues if an interface has several methods, or if other libraries extend that interface with additional methods. 

Off top of my head there are several options for us:

1. Convert interfaces to delegates, as you suggested. Probably selectively. 
1. Convert interfaces to classes, add constructor(s) with proper signatures, implicit operators e.g.:
```cs
public class FrameRequestCallback
{
   [Bridge.Template("{this}({0})")]
   void Self(double time);

   [Template("{0}")]
   public extern FrameRequestCallback(Action<double> callback);

   public static extern implicit operator FrameRequestCallback(Action<double> arg);
   public static extern implicit operator Action<double>(FrameRequestCallback arg);
}
```
3. Add overloads for methods having arguments of type `FrameRequestCallback` or similar:
```cs
public static extern double requestAnimationFrame(FrameRequestCallback callback);
public static extern double requestAnimationFrame(Action<double> callback);
// ...
```

The option 1 is the most simple and straightforward solution. We'll just have to ensure we don't break anything by that change.

**Comment by R2D221** [comment]
I think that the simplest case (an interface with a single call signature) can safely be converted to a delegate, but of course we would need to be 100% sure first. More complex cases could stay the way they are right now.

**Comment by chenxustu1** [comment]
thank you for your effort,but  is that posibble to provide source code of retyped package?
i encountered similar problem,
js code like this,
```
Notification.requestPermission(function (permission) {
      // If the user accepts, let's create a notification
      if (permission === "granted") {
        var notification = new Notification("Hi there!");
      }
    });
```
but c# code need to implement a abstract class :

```
public static extern es5.Promise<dom.NotificationPermission> requestPermission(dom.NotificationPermissionCallback callback);`

   [IgnoreCast]
    [Virtual]
    [FormerInterface]
    public abstract class NotificationPermissionCallback : IObject
    {
      [Template("{this}({0})")]
      public abstract void Self(dom.NotificationPermission permission);
    }
```

**Comment by AndreyChechel** [comment]
A related discussion of delegates represented by interfaces/classes:
https://forums.bridge.net/forum/general/extensions-and-plugins/5273-using-jquerydatatables-from-retyped

**Comment by AndreyChechel** [comment]
The feature is implemented, updated NuGet packages will be available in the upcoming release. Some details of the implementation:

1. If a type contains only one member, and that member is a `Self` method - the type will be replaced with a delegate declaration (as it was suggested in **option 1**)
1. If a type contains several members and all of them are `Self` methods - the type will be converted to a non-abstract class with the following members declared (as it was suggested in **option 2**):
   1. Original `Self` methods.
   1. Delegate types representing those `Self` methods.
   1. Constructor(s) having an argument of corresponding delegate type.
   1. Implicit conversion operator "to"/"from" declared delegate types.
   1. Implicit conversion operator "to" and an explicit "from" `System.Delegate` type.
1. If a type contains several members, and some of them are `Self` methods - the type will remain as is.
1. If a class is derived from a delegate type, it will get a `Self` method corresponding to that delegate type (constructors and implicit operators also might be added according to the rules above). The base delegate type will be removed from the base list to make the code compilable.
