### ISSUE TITLE
Consider processing notNeededPackages.json

### ISSUE THREAD

**Issue by Razenpok** [Retyped/Retyped#26]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/notNeededPackages.json

Basically, this file contains a list of packages that have their own TS definitions, and thus they are excluded from the DefinetlyTyped repository. Not sure if it's feasible to process them all, but some of them provide typings in the root of their repository (like https://github.com/primus/eventemitter3/blob/master/index.d.ts) and it would be pretty easy to provide support for them.

**Comment by geoffreymcgill** [comment]
Hi @Razenpok – Thanks for the suggestion. For the most part, supporting the **notNeededPackes**  can be easily added to Retyped. 

We have discussed this a few times, but I can't remember exactly why these were not supported from day 1. Probably just that we didn't have time to automate that part of the collection process. 

Other that @primus/eventemitter3, are there any other libraries you require?

**Comment by Razenpok** [comment]
Not really. I've just discovered Retyped (kudos for it) and decided to drop support of https://github.com/Razenpok/Bridge.Pixi and https://github.com/Razenpok/Bridge.EventEmitter3, but I couldn't find bindings for the latter, so here I am.

**Comment by AndreyChechel** [comment]
Hi @Razenpok,

The **notNeededPackages.json** file was added to Retyped as one more source of libraries providing TypeScript declarations. 

As for **EventEmitter3** library, a Retyped package for it was generated and uploaded to NuGet:
https://retyped.com/?q=eventemitter3#search
https://www.nuget.org/packages/retyped.eventemitter3
