### ISSUE TITLE
Leaflet.js

### ISSUE THREAD

**Issue by aschoenebeck** [Retyped/Retyped#27]
Please consider supporting the [Leaflet.js](http://leafletjs.com/) API.

I currently have hand crafted the external api for bridge. But it is for older versions and only supports the subset of types I needed. Keeping up to date with new releases is a lot of work. An automatically generated retyped package would make it so much easier.

[https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/leaflet](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/leaflet)

**Comment by AndreyChechel** [comment]
Hi @aschoenebeck,

Thanks for your interest in Bridge.NET and Retyped.

We will investigate why the library was not compiled to a Retyped package right away.
Looks like it's relatively easy to support it.

**Comment by AndreyChechel** [comment]
Hi @aschoenebeck,

**Leaflet.js** is now supported by Retyped. The package is now available on NuGet:
https://retyped.com/?q=leaflet.js
https://www.nuget.org/packages/retyped.leaflet
