### ISSUE TITLE
iMaya ZLIB.js

### ISSUE THREAD

**Issue by staras** [Retyped/Retyped#28]
Please consider supporting the [zlib.js](https://github.com/imaya/zlib.js/) API by iMaya.

I've been searching for a simple ZLIB library with retyped and haven't found one. I did find Pako, but I think it requires node.js which I don't currently need. If you know of another simple, fast and lightweight ZLIB API that is currently supported in Retyped than I'm fine using that as well.

Thank you for your consideration.

**Comment by geoffreymcgill** [comment]
Hi @staras – Thanks for the request. Do you know if TypeScript .d.ts files are available for ZLIB.js?

We would require the .d.ts file in order to support in Retyped.

**Comment by staras** [comment]
I'm not sure. I am not the author of this library. Do you know whether Retyped currently supports a simple, fast and lightweight ZLIB deflate, inflate API that doesn't have any other dependencies? I'm happy to use something else, but I just couldn't find anything when searching.

**Comment by geoffreymcgill** [comment]
I'm not really aware of a library with those features. It would be best to find something in the wild, then search [Retyped](https://retyped.com/?q=zip#search) if the library is supported. Retyped should be able to easily support any JavaScript library, but we require the .d.ts file to start.

**Comment by geoffreymcgill** [comment]
If the .d.ts files for this library are located, we'll take a look at creating a Retyped package. For now, I'm closing this issue.
