### ISSUE TITLE
Support MobX

### ISSUE THREAD

**Issue by geoffreymcgill** [Retyped/Retyped#29]
Request to support MobX library.

Resource | Location
---- | ----
Website | http://mobx.js.org/
GitHub | https://github.com/mobxjs/mobx
NPM | https://www.npmjs.com/package/mobx
Types | Available in NPM package

Please also include:

- [mobx-react](https://www.npmjs.com/package/mobx-react)
- [mobx-state-tree](https://www.npmjs.com/package/mobx-state-tree)
- [antd](https://www.npmjs.com/package/antd)

## See Also

* https://forums.bridge.net/forum/community/retyped/4925-retyped-for-mobx-mobx-state-tree-and-antd

**Comment by redbaty** [comment]
Up 👍

**Comment by stgolem** [comment]
May be we need support of @mweststrate here?

**Comment by mweststrate** [comment]
Note that the definitely typed definitions are quite ancient; up to date typings are provided by the npm pakages themselves trough the `typings` field.

**Comment by stgolem** [comment]
Totally agree with @mweststrate 
Your generator should respect `typings` field from `package.json`.
Up this 👍

**Comment by geoffreymcgill** [comment]
We're working on it.

**Comment by geoffreymcgill** [comment]
Looks like **Bridge.MobX** is almost ready. Should be published to NuGet this week.

**Comment by colderlord** [comment]
Gr8 news!
How about **mobx-react** and **mobx-state-tree** ?

**Comment by geoffreymcgill** [comment]
@colderlord - Post links to the official .d.ts files for the libraries and we'll take a look.

**Comment by AndreyChechel** [comment]
Retyped packages for **mobx** and **mobx-react** have been pushed to NuGet, closing the issue. 

As for the rest libraries mentioned in the description (**mobx-state-tree**, **antd**) - separate issues were created, see #46 and #47.

References:
* [MobX libraries](https://retyped.com/?q=mobx#search)
* [Retyped.mobx NuGet package](https://www.nuget.org/packages/retyped.mobx)
* [Retyped.mobx-react NuGet package](https://www.nuget.org/packages/retyped.mobx-react)

A simple demo project for **Retyped.mobx** is available here:
- [Live at Retyped demos](https://demos.retyped.com/dist/mobx/)
- [Sources](https://github.com/Retyped/Demos/tree/master/MobX)
