### ISSUE TITLE
phaser.js integration

### ISSUE THREAD

**Issue by woidl** [Retyped/Retyped#30]
phaser.js

Hello Community,
as geoffrey.mcgill wrote in forum about phaser.js integration, he recommends to add an issue for this.
So this is the issue...
Pleeeeease to all Retyped-gurus: If possible integrate the phaser.js game library into the bridge.net world! I think many game-developers will be very happy!

Many thnx for your great work done!
Gerhard

**Comment by geoffreymcgill** [comment]
Hi @woidl – Thanks for the request. 

Can you point us to the official (or best) **.d.ts** files for the project?

With those **.d.ts** files we can use Retyped to generate the binding library.

**Comment by Widerhold** [comment]
I'm also highly interested. The definitions file are located under https://github.com/photonstorm/phaser/tree/master/v2/typescript

Thank you in advance and for Bridge. it's awesome!

**Comment by geoffreymcgill** [comment]
Thanks for pointing out the location of the .d.ts files. 

They appear to be maintaining .d.ts files from other libraries (Pixi, p2, box2d) inside of the Phaser repo. That might complicate things a little. Would be much better if they just let those files be maintained with the original source library, or published separately to Definitely Typed. 

We're just finishing up a big revision to Retyped and will release in the next few days. Once that is complete, we will investigate adding support for Phaser.

**Comment by woidl** [comment]
Hi @geoffreymcgill and @Widerhold ,
sorry didn't expect that fast replys - many thnx for sending .d.ts.
Very sorry I'm not a phaser expert, just programming a little bit with it.
I have read some time ago in forum that next version of Phaser will be provided without Pixi, don't know what the actual state is, I'll try to investigate.

Thnx for trying to support Phaser :-)

**Comment by AndreyChechel** [comment]
Hi @woidl and @Widerhold,

We are glad to announce that Retyped now supports **Phaser.js**:
https://retyped.com/?q=phaser#search
https://www.nuget.org/packages/Retyped.phaser/

You might want to take a look on a [demo project](https://github.com/Retyped/Demos/tree/master/PhaserDemo) we created for **Retyped.phaser** package. Live demo is available [here](https://demos.retyped.com/dist/phaser/).

**Comment by Widerhold** [comment]
Awesome! Thank you very much @AndreyChechel

**Comment by woidl** [comment]
Hello guys from Retyped, really cool work!!!
Thank you all so much for integrating phaser that fast!
I'll start testing now...

**Comment by AndreyChechel** [comment]
@woidl thanks for the feedback!

We're also tracking Phaser repository - once they provide an updated .d.ts file, we will generate a Retyped package for it. Feel free to ping us regarding that.

Meanwhile we're working on syncing the rest Retyped packages with the latest declarations - so another "big push" is going to happen soon.

**Comment by woidl** [comment]
Ah ok, very nice to hear that, will update your packages then, thnx!

**Comment by SagarDabas** [comment]
Can we get latest update please.

**Comment by geoffreymcgill** [comment]
@SagarDabas – The last update to Retyped was on 2018-06-09, so this library would have been updated with the latest release at that time.

**Comment by SagarDabas** [comment]
Is there a way I could update it? Any suggestions, pls.
