### ISSUE TITLE
Q: Is this open source?

### ISSUE THREAD

**Issue by michaelcheers** [Retyped/Retyped#32]

**Comment by geoffreymcgill** [comment]
From the Retyped blog post [announcement](https://blog.bridge.net/2200-js-libraries-in-c-using-retyped-dcfafb28b119):

> License
> 
> Retyped packages are licensed under Apache-2.0 licence and are free to use in both commercial and open-source projects.
> 
> Licensing for use of the individual JavaScript libraries should be sourced from the original JavaScript library.
> Currently, the C# source code generated for each library by the Retyped compiler is not publicly available. We hope to release at some point in the future, but for now, they’re private. The NuGet Packages are public, the C# source code for each package is private.
> 
> The Retyped parser and compiler source code is private.

**Comment by michaelcheers** [comment]
@geoffreymcgill, thanks for the quick response.

**Comment by michaelcheers** [comment]
@geoffreymcgill, can you compile your own typescript files with it?
