### ISSUE TITLE
missing definition file for qlik-engineapi

### ISSUE THREAD

**Issue by thomashaenig** [Retyped/Retyped#34]
Hi, 

i miss the definition file for the qlik-engineapi. in the definition fils from node it does exist.

![image](https://user-images.githubusercontent.com/17725886/32841543-e52cfffc-ca1a-11e7-9edc-2f32fd9fb6bd.png)

**Comment by AndreyChechel** [comment]
Hi @thomashaenig,

Thanks for that request.
We'll investigate the possibility of supporting this library by Retyped.

**Comment by AndreyChechel** [comment]
Hi @thomashaenig,

The library **qlik-engineapi** is now supported by Retyped. The package is available on NuGet:
https://retyped.com/?q=qlik-engineapi#search
https://www.nuget.org/packages/retyped.qlik-engineapi
