### ISSUE TITLE
Phaser.js Timer not working

### ISSUE THREAD

**Issue by Widerhold** [Retyped/Retyped#35]
Hello,

i'm currently testing the new Phaser.js Retyped that you provided and so far it seems to work perfect except for the timer events.
I created an example:
https://gist.github.com/Widerhold/4f7ea818fc5e800de0ccb9990aa23418
The line `_timer = game.time.events.loop(1500, () => AddRowOfPipes(), this);` does not call the supplied function. It should call the function every 1.5 seconds. 
I tried other kinds of  Phaser.js Timer calls, nothing worked. 
It does not throw any errors.
Maybe i'm just using it wrong.

Thank you in advanced.

**Comment by geoffreymcgill** [comment]
Thanks for letting us know. We'll have a look and try to figure out what's going wrong. 

Sometimes these issues are caused when defects are present in the original/official .d.ts. If that's the case, we _might_ be able to work around the problem, but the better option is to get the source .d.ts fixed.

We'll figure out what's happening first.

If you were writing that line in JavaScript, how would it be written?

**Comment by AndreyChechel** [comment]
Working fine for me:
![image](https://user-images.githubusercontent.com/16582701/32888893-e0182874-cad9-11e7-91a4-9de64f82a56f.png)

**Comment by AndreyChechel** [comment]
@Widerhold, what version of Phaser.js do you use?

**Comment by Widerhold** [comment]
Oh okay, then something other must be wrong on my system. 
Sorry for bothering you. 
My phaser.js version is 2.62 just like in the Invader example. 
I tried with newer versions with no difference.
Nevertheless thank you for your efforts.

**Comment by geoffreymcgill** [comment]
Closing the issue for now. Feel free to re-open if you determine there's a defect somewhere.
