### ISSUE TITLE
Can't seem to use libraries with hyphens in their names.

### ISSUE THREAD

**Issue by bigloudjeff** [Retyped/Retyped#36]
I cannot figure out how to use libraries from retyped that have hyphens in their names.

Example: **Retyped.electron-json-storage**

C# code

```cs
using System;
using System.Collections.Generic;
using Bridge;
using Retyped;

namespace TestApp
{
    class Test
    {
        private static List<string> GetUrlList()
        {
            List<string> urls = null;

            electron_json_storage.get("UrlList", (error, data) =>
            {
                if (data != null)
                {
                    urls = (List<string>) data.ValueOf();
                }
                else
                {
                    urls = new List<string>();
                }
            });

            return urls;
        }
    }
}
```

Compiled javascript:

```js

Bridge.assembly("StaffHubDesktop", function ($asm, globals) {
    "use strict";

    var electron-json-storage = require("electron-json-storage");

    Bridge.define("TestApp.Test", {
        statics: {
            methods: {
                GetUrlList: function () {
                    var urls = null;

                    electron-json-storage.get("UrlList", function (error, data) {
                        if (data != null) {
                            urls = Bridge.cast(data.valueOf(), System.Collections.Generic.List$1(System.String));
                        } else {
                            urls = new (System.Collections.Generic.List$1(System.String)).ctor();
                        }
                    });

                    return urls;
                }
            }
        }
    });
});
```

I am using the ComonJS loader but the problem also occurs with the AMD loader.

Notice the hyphens in the variable that is declared during the "require".

```js
var electron-json-storage = require("electron-json-storage");
```

This is obviously an invalid token / variable name. 

I have tried fixing this via a named using declaration. i.e.
```cs
using Storage = Retyped.electron_json_storage;
```

But it just gets replaced with the same invalid token with hyphens in the name.

Am I missing some other setting or usage that would correct this issue or should this be considered a bug?

Thanks,

Jeff

**Comment by AndreyChechel** [comment]
Hi @bigloudjeff,

Thanks for letting us know about that. We will investigate.

**Comment by bigloudjeff** [comment]
Should I cross-post this to the Bridge.Net issues list? I'm not sure why I posted it here in retyped since it seems like it could be fixed in the bridge compiler.

**Comment by AndreyChechel** [comment]
Whereas it's possible to fix naming issue in Bridge, I think we'd better to fix that at Retyped end. The reason of the defect is the way how a module is declared by Retyped:

```cs
[assembly: Bridge.Module(Bridge.ModuleType.UMD, Name = "electron-json-storage")]
```

Take a look at the **Name** property, Retyped puts the original library name there without escaping. And Bridge uses that value as is, because it assumes the provided value is correct.

Unfortunately, we have not found any workarounds for this defect, so we'll have to republish all packages with the fixed naming as soon as possible. Hopefully this weekend.

**Comment by bigloudjeff** [comment]
Great! Please let me know if there is anything I can do to help. Thanks!

**Comment by AndreyChechel** [comment]
Hi @bigloudjeff,

We've fixed the defect with naming, all Retyped packages have been regenerated and pushed to NuGet.
Your scenario must be working now after you refresh the dependencies.

**Comment by bigloudjeff** [comment]
Works great now. Thanks!
