### ISSUE TITLE
Devextrem support?

### ISSUE THREAD

**Issue by volkanalkilic** [Retyped/Retyped#37]
Please add support for Devextreme

**Comment by geoffreymcgill** [comment]
Can you link us to the official public .d.ts files for the project?

**Comment by geoffreymcgill** [comment]
We found the following .d.ts which appears to be the official release:

https://github.com/DevExpress/DevExtreme/blob/17_2/ts/dx.all.d.ts

It's unclear whether their licensing model allows for Retyped to create a package based on this d.ts, so we'll have to spend some time reviewing their [LICENSE.md](https://github.com/DevExpress/DevExtreme/blob/17_2/LICENSE.md).

**Comment by dragnilar** [comment]
I really hope you can get Devextreme to work with Bridge.NET. While I'm not sure if their license will allow it, I think it wouldn't hurt to ask them. They're pretty nice people.

**Comment by geoffreymcgill** [comment]
The DevExtreme [.d.ts](https://github.com/DevExpress/DevExtreme/blob/17_2/ts/dx.all.d.ts) is not stamped with a specific License, so we have to assume the file is covered by their **[DevExpress Non-Commercial, Non-Competitive License](https://github.com/DevExpress/DevExtreme/blob/17_2/LICENSE.md)**.

Unfortunately, after reading the whole LICENSE.md, it's very unclear to me whether Retyped would be permitted to create a _Derivative Work_ from the source .d.ts.

We don't have the resources to determine whether Retyped is a permitted use, so we'll have to pass on adding this library to Retyped.

@dragnilar – These licensing questions are best submitted to DevExpress. Maybe they can provide some direction. If you can get someone from DevExpress to approve the use of creating a Retyped library from the .d.ts, and provide that written approval within this thread, then adding DevExtreme support to Retyped will be very quick and simple.

I'm going to close this thread for now but will be happy to re-open once some direction regarding the licensing becomes clear.
