### ISSUE TITLE
Retyped.Phaser not being built

### ISSUE THREAD

**Issue by a20eac1d** [Retyped/Retyped#38]
I am using the official setup guide on the Retyped website in combination with [this example](https://github.com/Retyped/Demos/tree/master/PhaserDemo) to setup a Phaser game project.

I have installed the following Nuget packages and their dependencies:
- Bridge
- Retyped
- Retyped.phaser

All packages are using the latest versions.

Issue: When building the project, a "Retyped.phaser.dll" will be built into "/Debug", but no .js file will be created in "/Debug/bridge". As a result of this, the Javascript-Console will show [multiple errors](https://i.imgur.com/mX7P1AV.png), they main one being "Uncaught ReferenceError: Phaser is not defined" (because phaser.js is missing). The HTML file that is being created only references [a few .js files.](https://pastebin.com/3D1aFq64)

Is this an issue with my setup? If so, how can I fix it?
If not, do you need anything else to fix this issue?

Let me know!

**Comment by AndreyChechel** [comment]
Hi @a20eac1d,

The first place we should look at is `output` setting in **bridge.json** file. The example you mentioned outputs all scripts outside the solution folder:
```
"output": "../../dist/phaser/js/"
```

The output folder will contain JavaScript sources generated for your C# project. However, those scripts do not include sources for Retyped libraries you referenced - they should be provided manually. In the **Phaser** sample, **phaser.js** script is being loaded from [CDNJS](https://github.com/Retyped/Demos/blob/3b965024d4835fa4fc35a225b6d5cf07c1f35229/dist/phaser/index.html#L9). In the future, Retyped packages will include JavaScript sources, that task has high priority for us.

Please let us know whether the suggestions above helped.

**Comment by a20eac1d** [comment]
@AndreyChechel I am now providing the phaser.js manually and it works! Thank you!

But I stumbled upon another issue but I'm not sure if this is the right place to discuss it. Even though I am creating a 640x480 phaser game, it is displaying it in 800x600 which is due to my Windows DPI Scaling of 125%. Do you know if is this due to an issue with Retyped or is it Phaser?

Thanks in advance!

**Comment by AndreyChechel** [comment]
I don't think this issue is related to Retyped, so you'd better ask **Phaser.js** community for help .

Just in case - this is how I was able to change the "Space Invaders" game frame size:
```cs
_starfield = game.add.tileSprite(0, 0, 640, 480, "starfield");
this.scale.setGameSize(640, 480);
```

**Comment by a20eac1d** [comment]
It seems like the issue is actually caused by Chrome, not Phaser. Weird. Thank you!
