### ISSUE TITLE
Please update ej.web.all from DefinitelyTyped repo to 15.4.

### ISSUE THREAD

**Issue by CastleSoft** [Retyped/Retyped#40]
Older version 15.2 in Retyped, please update to DefinitelyTyped 15.4

**Found in:**
- [LibraryURL](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ej.web.all)

**Comment by geoffreymcgill** [comment]
We have updated Retyped to support TypeScript 2.7 (latest release) and are now in the process of updating to the latest DefinitelyTyped libraries. Once we have everything compiling correctly, we will release new packages for all libraries.

**Comment by AndreyChechel** [comment]
Hi @CastleSoft,

The **Retyped.ej.web.all** package was updated to the latest version (16.1).
The package is available on NuGet: 
https://retyped.com/?q=ej.web.all#search
https://www.nuget.org/packages/retyped.ej.web.all
