### ISSUE TITLE
The type name 'Platform' does not exist in the type 'node.Literals.Options'

### ISSUE THREAD

**Issue by stamhaney** [Retyped/Retyped#44]
The Widgetoko code refers to Retyped.node.Literals.Options.Platform . If I update Bridge.Net to the latest version, I get a load of errors like 
1) Error	11	) expected
2) Error	12	; expected	
3) Error	2	Invalid expression term '.'
4) Error	18	The type name 'Platform' does not exist in the type 'node.Literals.Options'

The code was not modified. The solution uses the same code, just Bridge.Net has been updated

Can you tell me how to resolve this error? I am a newbie using Retyped, Bridge.Net

Thanks

**Comment by geoffreymcgill** [comment]
Hi @stamhaney Thanks for the report. We will take a look at the Widetoko project and see if we can determine what's going wrong.

We'll keep this thread updated on our progress.

**Comment by AndreyChechel** [comment]
[Widgetoko](https://github.com/bridgedotnet/Widgetoko) app has been updated.

The reason of the error was an incorrect location of **Platform** enum. Currently it is:
`Retyped.node.NodeJS.Platform`.

The previously used `node.Literals.Options.Platform` is not longer available due to fix for #33
