### ISSUE TITLE
aspnet blazor

### ISSUE THREAD

**Issue by grahamehorner** [Retyped/Retyped#48]
Please consider support aspnet core and/or working with the aspnet Blazor project to allow use of the generated C# files for interop stubs for Blazor WASM projects

## See Also

* https://github.com/aspnet/Blazor/issues/37

**Comment by geoffreymcgill** [comment]
Thanks for the suggestion!

**Comment by geoffreymcgill** [comment]
Blazor (et al.) is just too much of a moving target for us to invest resources into right now. It would be nice to see Microsoft support Retyped instead.

**Comment by grahamehorner** [comment]
Is Retyped and the toolset still going to be open sourced ?

**Comment by geoffreymcgill** [comment]
Our goal is to open-source the Retyped toolset at some point, but we don't have a clear picture of when that could be. For now, it's still in private development.

**Comment by geoffreymcgill** [comment]
I took another look at this topic today. It appears the Microsoft team is working on something in this space. It looks like we could extend Retyped to support Mono/WASM/Blazor, although it's really tough to justify investing the time to support the platform if they're already building something.

The next release of Retyped should ship soon and will support >3000 libraries. Ultimately, if there are features supported by Retyped but not supported by the Microsoft solution, maybe we could take a close look at how Retyped could bring some additional value to the platforms. For time being, we just don't have the resources available to invest in extending Retyped to support Mono/WASM/Blazor.
