### ISSUE TITLE
VisJS

### ISSUE THREAD

**Issue by rafael-aero** [Retyped/Retyped#49]
Request to support vis.js library.

| Resource | Location |
| --------- | -------- | 
| Website | http://visjs.org/ |
| GitHub | https://github.com/almende/vis |
| NPM | https://www.npmjs.com/package/vis |
| Types | https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vis/index.d.ts |

## See Also

- https://forums.bridge.net/forum/community/retyped/5222-support-for-vis-js

**Comment by geoffreymcgill** [comment]
@rafael-aero – Thanks for making this request. We'll review the .d.ts files and attempt to create the Retyped package right away.

**Comment by rafael-aero** [comment]
@geoffreymcgill awesome, looking forward to it!

**Comment by AndreyChechel** [comment]
Hi @rafael-aero,

**Vis.js** library was supported, **Retyped.vis** package is available on NuGet now:
https://retyped.com/?q=vis.js%20#search
https://www.nuget.org/packages/retyped.vis

We also added a demo project with a few samples from the official website:
https://demos.retyped.com
https://github.com/Retyped/Demos/tree/master/VisJsDemo
