### ISSUE TITLE
Retyped.dom MutationObserver should be improved

### ISSUE THREAD

**Issue by danieldegtyarev** [Retyped/Retyped#51]
Expected: constructor of MutationObserver should take callback method as a parameter.
Actual: MutationObserver required an instance of a class with Self method.
Workaround: create Action<X,Y>, cast to object, recast to that special class

**Comment by geoffreymcgill** [comment]
Hi @danieldegtyarev – This is the current .cs that is generated for **MutationObserver** in Retyped. What revision to the .cs are you recommending?

```csharp
public class MutationObserver
{
    public extern MutationObserver(MutationCallback callback);

    // other members removed
}

public abstract class MutationCallback
{
    [Bridge.Template("{this}({0}, {1})")]
    public abstract void Self(Retyped.dom.MutationRecord[] mutations, Retyped.dom.MutationObserver observer);
}
```

**Comment by AndreyChechel** [comment]
Related to #25. We're working on that issue, should be fixed soon.

**Comment by AndreyChechel** [comment]
The feature is implemented, updated NuGet packages will be available in the upcoming release. 
See #25 for more details.
