### ISSUE TITLE
Wrong deprecated status for Retyped.jQuery.

### ISSUE THREAD

**Issue by hardhub** [Retyped/Retyped#62]
A lot of functions has @deprecated 3.3 in comments:  

```
 /// <summary>
      /// Bind an event handler to the "scroll" JavaScript event, or trigger that event on an element.
      /// @since 1.4.3
      /// @deprecated 3.3
      /// </summary>
      /// <param name="eventData">An object containing data that will be passed to the event handler.</param>
      /// <param name="handler">A function to execute each time the event is triggered.</param>
```

But in 3.3 we have only 2 functions deprecated:  
https://api.jquery.com/category/deprecated/deprecated-3.3/

_jQuery.isFunction()
jQuery.isWindow()_

So for example _scroll_ is not deprecated: https://api.jquery.com/scroll/

**Comment by AndreyChechel** [comment]
This one is not a Retyped issue. Those comments are originated from [DefinitelyTyped/jquery.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/932727f5785b3bdab808da5852467358dc09d588/types/jquery/index.d.ts#L223).

Please raise the issue in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) repository. Once they update the declaration file, we'll regenerate the **Retyped.jquery** NuGet package.
