### ISSUE TITLE
retyped.jquery.JQuery class changed from normal class to a static class

### ISSUE THREAD

**Issue by Hopfenspirger** [Retyped/Retyped#77]
retyped.jquery.JQuery class changed from normal class to a static class. How to create extensions now? I used to use the following code…

```csharp
public static jquery.JQuery kendoButton(this jquery.JQuery jQuery) {
    return null;
}
```

this is not working with a static class. How can I extend jQuery now?

**Comment by AndreyChechel** [comment]
It's now a generic class, so it maps better to the interface in [jquery.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/932727f5785b3bdab808da5852467358dc09d588/types/jquery/index.d.ts#L3101) (Line 3101).

```cs
[Bridge.Where(nameof(TElement), typeof (Retyped.dom.Node.Interface)]
public abstract class JQuery<TElement> : Iterable<TElement>
{
    // ...
}
```

You'll need to add generic type parameter to make your extensions working:
```cs
[External]
public static class Extensions
{
    public static extern jquery.JQuery<T> kendoButton<T>(this jquery.JQuery<T> jQuery);
}
```

**Comment by Hopfenspirger** [comment]
Thanks for the quick answer. This is working for me. 

Just as an info: It took me around 4 hours to refactor my project (it is a small project with around 60 000 lines of code). Not only because of this change but there were a couple of other changes which needed refactoring. I think: Such changes will prefent the use of bridge.net in bigger projects... at least for me.

**Comment by geoffreymcgill** [comment]
> Just as an info: It took me around 4 hours to refactor my project (it is a small project with around 60 000 lines of code). Not only because of this change but there were a couple of other changes which needed refactoring. I think: Such changes will prefent the use of bridge.net in bigger projects... at least for me.

Thanks for the feedback, although what would be of assistance to the project is any specific feedback you might have. Generalized statements are tough to do anything with but outlining specific problem scenarios is something we can likely act upon.

**Comment by Hopfenspirger** [comment]
Here are the details:

Needed refactorings were:
(Sorry, but I don't know the version I had before, but it was from around Summer 2018)

**Version (Around Summer 2018) -> 17.8**
- JQuery -> JQuery<T>
- string HTMLElement.attr(string) - Union(<string>,<undefined>) attr(string)
- jElement.bind(string, Func<object>) -> jElement.bind(string, Func<object, ???>)
- jquery.@select(string) -> added a couple of overloads so calling it with dynamic types is not possible any more
