### ISSUE TITLE
Question regarding the project

### ISSUE THREAD

**Issue by NickAcPT** [Retyped/Retyped#83]
Hello, I'm writing here to ask the following question:
> Is the code for this project (the parser and converter) ever going to be open sourced?

It was asked back in 2017 in #32, but I'd rather ask again to see if anything has changed.

**Comment by geoffreymcgill** [comment]
Hi @NickAcPT. Unfortunately, it doesn't look like Retyped will be open-sourced.

**Comment by NickAcPT** [comment]
@geoffreymcgill That is such a shame. Like maybe have mentioned in the past, we would all benefit from being able to parse TS definitions and create C# symbols for them.

One really obvious case would be Blazor. Will it be reconsidered in the future?
