### ISSUE TITLE
Missing ej.web.all  (Syncfusion controls)

### ISSUE THREAD

**Issue by CastleSoft** [Retyped/Retyped#9]
Missing Syncfusion wrapper for ej.web.all

**Found in:**
- [ej.web.all](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ej.web.all)

**Comment by AndreyChechel** [comment]
Hi @CastleSoft,

Thanks for reporting this issue. We are investigating the possibility to create a package for that library. We'll let you know once the package is available on NuGet.

**Comment by CastleSoft** [comment]
Thanks..


________________________________

**Comment by geoffreymcgill** [comment]
Just a quick update... we have this library working and will be publishing the NuGet package soon. 

Once the package has been published, we will close this issue.

**Comment by AndreyChechel** [comment]
The package has been published:
https://retyped.com/?q=ej.web.all#search

**Comment by geoffreymcgill** [comment]
Live Demo: 
https://demos.retyped.com/dist/syncfusion/

Demo Source Code:
https://github.com/Retyped/Demos/tree/master/SyncfusionDemo
